### PR TITLE
Upgrade to jwilder/nginx-proxy 1.3-alpine

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
A bit older by now, this PR…

**Comment by kdambekalns** [comment]
1.3 would be current…

**Comment by robertlemke** [comment]
And does it still work?

**Comment by kdambekalns** [comment]
I'll update even more and check now… 😎

**Comment by kdambekalns** [comment]
Now with 1.3 inside, I built this locally and used it to successfully run Local Beach.

To test it, one needs to build an adjusted binary that includes the test version… I did:

```
docker build .
docker tag d6e67de0b62fa997aa524314253859c3dc0c42f1a6b546e3eafb48f043d69bfa flownative/localbeach-nginx-proxy:dev
```

and then in Local Beach edit `assets/local-beach/docker-compose.yml` to use the `dev` version. Then restart Local Beach using that binary and you should see the dev vrsion being used in `~/.LocalBeach/docker-compose.yml` (and in `docker ps`)

**Comment by kdambekalns** [comment]
Ping…

**Review by robertlemke — APPROVED** [review]
Seems to work.

**Pull request merged**
